import sbt._
import Keys._

object SbtTestBuild extends Build {

	val cleanAll = TaskKey[Unit]("clean-all", "Removes all autogenerated files.")
	val dist = TaskKey[Unit]("dist", "Produce a distribution.")

	lazy val root = Project("root", file("."))
}
